/*
 * +----------------------------------------------------------------------------------------------+
 * The Metadata structure
 * Date - January 2017
 * Author - Pradyumna P. Saraph
   +----------------------------------------------------------------------------------------------+
 */
using NLog;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Script.Serialization;

namespace ItantProcessor
{
    class CDataMetaStructure
    {
        public void AddColData(Dictionary<string, object> objDataRow)
        {
            foreach (KeyValuePair<string, object> datafield in objDataRow)
            {
                string strDataField = datafield.Key;
                string strType = GetFieldType(datafield.Value);
                m_ObjMetaStructure.Add(strDataField, strType);
            }
        }

        public string GetJSON()
        {
            LOGGER.Info("Getting Column info JSON");
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            ConvertMetaStructToColInfo();
            return serializer.Serialize(m_objColInfo);
        }

        public void AddColData(string strKey, string strValue)
        {
            m_ObjMetaStructure.Add(strKey, strValue);
        }

        private string GetFieldType(object val)
        {
            string strType = "text";
            string strDataVal = Regex.Replace(Convert.ToString((val)), @"\s+", " ", RegexOptions.Multiline);
            DateTime dt = DateTime.UtcNow;
            if(DateTime.TryParseExact(strDataVal,formats,
                             CultureInfo.InvariantCulture,
                             DateTimeStyles.AssumeLocal | DateTimeStyles.AllowWhiteSpaces,
                             out dt))
            {
                strType = "time";
            } else
            {
                try
                {
                    Convert.ToInt32(strDataVal);
                    strType = "number";
                } 
                catch(Exception ex)
                {
                   try
                    {
                        LOGGER.Debug(ex.ToString());
                        LOGGER.Warn("Failed to convert to number, trying decimal");
                        Decimal.Parse(strDataVal);
                        strType = "number";    
                    }
                    catch (Exception ex1)
                    {
                        LOGGER.Debug(ex1.ToString());
                        LOGGER.Warn("Field was not converted to Number so it is text");
                        strType = "text";
                    }
                }
            }
            return strType;
        }

        private void ConvertMetaStructToColInfo()
        {
            foreach(KeyValuePair<string,string> objRec in m_ObjMetaStructure)
            {
                m_objColInfo.Add(new ColumInfo() { name = objRec.Key, type = objRec.Value });
            }
        }


        private Dictionary<string, string> m_ObjMetaStructure = new Dictionary<string,string>();
        private List<ColumInfo> m_objColInfo = new List<ColumInfo>();
        private static String[] formats = new[] {
                                                    "M/dd/yyyy hh:mm:ss tt",
                                                    "d/M/yyyy h:mm:ss tt",
                                                    "d/M/yyyy h:mm tt",
                                                    "dd/MM/yyyy hh:mm:ss",
                                                    "d/M/yyyy h:mm:ss",
                                                    "d/M/yyyy hh:mm tt",
                                                    "d/M/yyyy hh tt",
                                                    "d/M/yyyy h:mm",
                                                    "d/M/yyyy h:mm",
                                                    "dd/MM/yyyy hh:mm",
                                                    "d/MM/yyyy hh:mm",
                                                    "d/MM/yyyy h:mm:ss,FFF",
                                                    "d/MM/yyyy hh:mm:ss,FFF",
                                                    "d/MM/yyyy h:mm:ss tt,FFF",
                                                    "d/MM/yyyy hh:mm:ss tt,FFF",
                                                    "d/M/yyyy h:mm:ss,FFF",
                                                    "d/M/yyyy hh:mm:ss,FFF",
                                                    "d/M/yyyy h:mm:ss tt,FFF",
                                                    "dd/M/yyyy hh:mm:ss tt,FFF",
                                                    "dd/M/yyyy h:mm:ss,FFF",
                                                    "dd/M/yyyy hh:mm:ss,FFF",
                                                    "dd/M/yyyy h:mm:ss tt,FFF",
                                                    "dd/M/yyyy hh:mm:ss tt,FFF",
                                                    "d-M-yyyy h:mm:ss tt",
                                                    "d-M-yyyy h:mm tt",
                                                    "dd-MM-yyyy hh:mm:ss",
                                                    "d-M-yyyy h:mm:ss",
                                                    "d-M-yyyy hh:mm tt",
                                                    "d-M-yyyy hh tt",
                                                    "d-M-yyyy h:mm",
                                                    "d-M-yyyy h:mm",
                                                    "dd-MM-yyyy hh:mm",
                                                    "d-MM-yyyy hh:mm",
                                                    "d-MM-yyyy h:mm:ss,FFF",
                                                    "d-MM-yyyy hh:mm:ss,FFF",
                                                    "d-MM-yyyy h:mm:ss tt,FFF",
                                                    "d-MM-yyyy hh:mm:ss tt,FFF",
                                                    "d-M-yyyy h:mm:ss,FFF",
                                                    "d-M-yyyy hh:mm:ss,FFF",
                                                    "d-M-yyyy h:mm:ss tt,FFF",
                                                    "d-M-yyyy hh:mm:ss tt,FFF",
                                                    "dd-M-yyyy hh:mm:ss tt,FFF",
                                                    "dd-M-yyyy h:mm:ss,FFF",
                                                    "dd-M-yyyy hh:mm:ss,FFF",
                                                    "dd-M-yyyy h:mm:ss tt,FFF",
                                                    "dd-M-yyyy hh:mm:ss tt,FFF",
                                                    "M/d/yyyy h:mm:ss tt",
                                                    "M/d/yyyy h:mm tt",
                                                    "MM/dd/yyyy hh:mm:ss",
                                                    "M/d/yyyy h:mm:ss",
                                                    "M/d/yyyy hh:mm tt",
                                                    "M/d/yyyy hh tt",
                                                    "M/d/yyyy h:mm",
                                                    "M/d/yyyy h:mm",
                                                    "MM/dd/yyyy hh:mm",
                                                    "M/dd/yyyy hh:mm",
                                                    "M/dd/yyyy h:mm:ss,FFF",
                                                    "M/dd/yyyy hh:mm:ss,FFF",
                                                    "M/dd/yyyy h:mm:ss tt,FFF",
                                                    "M/dd/yyyy hh:mm:ss tt,FFF",
                                                    "M/d/yyyy h:mm:ss,FFF",
                                                    "M/d/yyyy hh:mm:ss,FFF",
                                                    "M/d/yyyy h:mm:ss tt,FFF",
                                                    "MM/d/yyyy hh:mm:ss tt,FFF",
                                                    "MM/d/yyyy h:mm:ss,FFF",
                                                    "MM/d/yyyy hh:mm:ss,FFF",
                                                    "MM/d/yyyy h:mm:ss tt,FFF",
                                                    "MM/d/yyyy hh:mm:ss tt,FFF",
                                                    "M-d-yyyy h:mm:ss tt",
                                                    "M-d-yyyy h:mm tt",
                                                    "MM-dd-yyyy hh:mm:ss",
                                                    "M-d-yyyy h:mm:ss",
                                                    "M-d-yyyy hh:mm tt",
                                                    "M-d-yyyy hh tt",
                                                    "M-d-yyyy h:mm",
                                                    "M-d-yyyy h:mm",
                                                    "MM-dd-yyyy hh:mm",
                                                    "M-dd-yyyy hh:mm",
                                                    "M-dd-yyyy h:mm:ss,FFF",
                                                    "M-dd-yyyy hh:mm:ss,FFF",
                                                    "M-dd-yyyy h:mm:ss tt,FFF",
                                                    "M-dd-yyyy hh:mm:ss tt,FFF",
                                                    "M-d-yyyy h:mm:ss,FFF",
                                                    "M-d-yyyy hh:mm:ss,FFF",
                                                    "M-d-yyyy h:mm:ss tt,FFF",
                                                    "M-d-yyyy hh:mm:ss tt,FFF",
                                                    "MM-d-yyyy hh:mm:ss tt,FFF",
                                                    "MM-d-yyyy h:mm:ss,FFF",
                                                    "MM-d-yyyy hh:mm:ss,FFF",
                                                    "MM-d-yyyy h:mm:ss tt,FFF",
                                                    "MM-d-yyyy hh:mm:ss tt,FFF",
                                                    "yyyy/d/M h:mm:ss tt",
                                                    "yyyy/d/M h:mm tt",
                                                    "yyyy/dd/MM hh:mm:ss",
                                                    "yyyy/d/M h:mm:ss",
                                                    "yyyy/d/M hh:mm tt",
                                                    "yyyy/d/M hh tt",
                                                    "yyyy/d/M/ h:mm",
                                                    "yyyy/d/M h:mm",
                                                    "yyyy/dd/MM hh:mm",
                                                    "yyyy/d/MM hh:mm",
                                                    "yyyy/d/MM h:mm:ss,FFF",
                                                    "yyyy/d/MM hh:mm:ss,FFF",
                                                    "yyyy/d/MM h:mm:ss tt,FFF",
                                                    "yyyy/d/MM hh:mm:ss tt,FFF",
                                                    "yyyy/d/M h:mm:ss,FFF",
                                                    "yyyy/d/M hh:mm:ss,FFF",
                                                    "yyyy/d/M h:mm:ss tt,FFF",
                                                    "yyyy/dd/M hh:mm:ss tt,FFF",
                                                    "yyyy/dd/M h:mm:ss,FFF",
                                                    "yyyy/dd/M hh:mm:ss,FFF",
                                                    "yyyy/dd/M h:mm:ss tt,FFF",
                                                    "yyyy/dd/M hh:mm:ss tt,FFF",
                                                    "yyyy/MM/dd hh:mm",
                                                    "yyyy/MM/d hh:mm",
                                                    "yyyy/MM/d h:mm:ss,FFF",
                                                    "yyyy/MM/d hh:mm:ss,FFF",
                                                    "yyyy/MM/d h:mm:ss tt,FFF",
                                                    "yyyy/MM/d hh:mm:ss tt,FFF",
                                                    "yyyy/M/d h:mm:ss tt",
                                                    "yyyy/M/d h:mm tt",
                                                    "yyyy/MM/dd hh:mm:ss",
                                                    "yyyy/M/d h:mm:ss",
                                                    "yyyy/M/d hh:mm tt",
                                                    "yyyy/M/d hh tt",
                                                    "yyyy/M/d h:mm",
                                                    "yyyy/M/d h:mm",
                                                    "yyyy/M/d h:mm:ss,FFF",
                                                    "yyyy/M/d hh:mm:ss,FFF",
                                                    "yyyy/M/d h:mm:ss tt,FFF",
                                                    "yyyy/M/dd hh:mm:ss tt,FFF",
                                                    "yyyy/M/dd h:mm:ss,FFF",
                                                    "yyyy/M/dd hh:mm:ss,FFF",
                                                    "yyyy/M/dd h:mm:ss tt,FFF",
                                                    "yyyy/M/dd hh:mm:ss tt,FFF",
                                                    "yyyy-d-M h:mm:ss tt",
                                                    "yyyy-d-M h:mm tt",
                                                    "yyyy-dd-MM hh:mm:ss",
                                                    "yyyy-d-M h:mm:ss",
                                                    "yyyy-d-M hh:mm tt",
                                                    "yyyy-d-M hh tt",
                                                    "yyyy-d-M- h:mm",
                                                    "yyyy-d-M h:mm",
                                                    "yyyy-dd-MM hh:mm",
                                                    "yyyy-d-MM hh:mm",
                                                    "yyyy-d-MM h:mm:ss,FFF",
                                                    "yyyy-d-MM hh:mm:ss,FFF",
                                                    "yyyy-d-MM h:mm:ss tt,FFF",
                                                    "yyyy-d-MM hh:mm:ss tt,FFF",
                                                    "yyyy-d-M h:mm:ss,FFF",
                                                    "yyyy-d-M hh:mm:ss,FFF",
                                                    "yyyy-d-M h:mm:ss tt,FFF",
                                                    "yyyy-dd-M hh:mm:ss tt,FFF",
                                                    "yyyy-dd-M h:mm:ss,FFF",
                                                    "yyyy-dd-M hh:mm:ss,FFF",
                                                    "yyyy-dd-M h:mm:ss tt,FFF",
                                                    "yyyy-dd-M hh:mm:ss tt,FFF",
                                                    "yyyy-MM-dd hh:mm",
                                                    "yyyy-MM-d hh:mm",
                                                    "yyyy-MM-d h:mm:ss,FFF",
                                                    "yyyy-MM-d hh:mm:ss,FFF",
                                                    "yyyy-MM-d h:mm:ss tt,FFF",
                                                    "yyyy-MM-d hh:mm:ss tt,FFF",
                                                    "yyyy-M-d h:mm:ss tt",
                                                    "yyyy-M-d h:mm tt",
                                                    "yyyy-MM-dd hh:mm:ss",
                                                    "yyyy-M-d h:mm:ss",
                                                    "yyyy-M-d hh:mm tt",
                                                    "yyyy-M-d hh tt",
                                                    "yyyy-M-d h:mm",
                                                    "yyyy-M-d h:mm",
                                                    "yyyy-M-d h:mm:ss,FFF",
                                                    "yyyy-M-d hh:mm:ss,FFF",
                                                    "yyyy-M-d h:mm:ss tt,FFF",
                                                    "yyyy-M-dd hh:mm:ss tt,FFF",
                                                    "yyyy-M-dd h:mm:ss,FFF",
                                                    "yyyy-M-dd hh:mm:ss,FFF",
                                                    "yyyy-M-dd h:mm:ss tt,FFF",
                                                    "yyyy-M-dd hh:mm:ss tt,FFF",

                                                    //date formats
                                                    "d/M/yyyy",
                                                    "d/MM/yyyy",
                                                    "dd/M/yyyy",
                                                    "dd/MM/yyyy",
                                                    "M/d/yyyy",
                                                    "MM/d/yyyy",
                                                    "M/dd/yyyy",
                                                    "MM/dd/yyyy",
                                                    "yyyy/M/d",
                                                    "yyyy/MM/d",
                                                    "yyyy/M/dd",
                                                    "yyyy/MM/dd",
                                                    "yyyy/d/M",
                                                    "yyyy/d/MM",
                                                    "yyyy/dd/M",
                                                    "yyyy/dd/MM",
                                                    "d-M-yyyy",
                                                    "d-MM-yyyy",
                                                    "dd-M-yyyy",
                                                    "dd-MM-yyyy",
                                                    "M-d-yyyy",
                                                    "MM-d-yyyy",
                                                    "M-dd-yyyy",
                                                    "MM-dd-yyyy",
                                                    "yyyy-M-d",
                                                    "yyyy-MM-d",
                                                    "yyyy-M-dd",
                                                    "yyyy-MM-dd",
                                                    "yyyy-d-M",
                                                    "yyyy-d-MM",
                                                    "yyyy-dd-M",
                                                    "yyyy-dd-MM",
                                                    //time formats
                                                    "h:mm:ss tt",
                                                    "h:mm tt",
                                                    "hh:mm:ss",
                                                    "hh:mm:ss tt",
                                                    "h:mm:ss",
                                                    "hh:mm tt",
                                                    "hh tt",
                                                    "h:mm",
                                                    "h:mm",
                                                    "hh:mm",
                                                    "hh:mm",
                                                    "h:mm:ss tt",
                                                    "h:mm tt",
                                                    "hh:mm:ss",
                                                    "h:mm:ss",
                                                    "hh:mm tt",
                                                    "hh tt",
                                                    "h:mm",
                                                    "h:mm",
                                                    "hh:mm",
                                                    "hh:mm",
                                                    "h:mm:ss,FFF",
                                                    "hh:mm:ss,FFF",
                                                    "h:mm:ss tt,FFF",
                                                    "hh:mm:ss tt,FFF",
                                                    "M/dd/yyyy HH:mm:ss tt",
                                                    "d/M/yyyy H:mm:ss tt",
                                                    "d/M/yyyy H:mm tt",
                                                    "dd/MM/yyyy HH:mm:ss",
                                                    "d/M/yyyy H:mm:ss",
                                                    "d/M/yyyy HH:mm tt",
                                                    "d/M/yyyy HH tt",
                                                    "d/M/yyyy H:mm",
                                                    "d/M/yyyy H:mm",
                                                    "dd/MM/yyyy HH:mm",
                                                    "d/MM/yyyy HH:mm",
                                                    "d/MM/yyyy H:mm:ss,FFF",
                                                    "d/MM/yyyy HH:mm:ss,FFF",
                                                    "d/MM/yyyy H:mm:ss tt,FFF",
                                                    "d/MM/yyyy HH:mm:ss tt,FFF",
                                                    "d/M/yyyy H:mm:ss,FFF",
                                                    "d/M/yyyy HH:mm:ss,FFF",
                                                    "d/M/yyyy H:mm:ss tt,FFF",
                                                    "dd/M/yyyy HH:mm:ss tt,FFF",
                                                    "dd/M/yyyy H:mm:ss,FFF",
                                                    "dd/M/yyyy HH:mm:ss,FFF",
                                                    "dd/M/yyyy H:mm:ss tt,FFF",
                                                    "dd/M/yyyy HH:mm:ss tt,FFF",
                                                    "d-M-yyyy H:mm:ss tt",
                                                    "d-M-yyyy H:mm tt",
                                                    "dd-MM-yyyy HH:mm:ss",
                                                    "d-M-yyyy H:mm:ss",
                                                    "d-M-yyyy HH:mm tt",
                                                    "d-M-yyyy HH tt",
                                                    "d-M-yyyy H:mm",
                                                    "d-M-yyyy H:mm",
                                                    "dd-MM-yyyy HH:mm",
                                                    "d-MM-yyyy HH:mm",
                                                    "d-MM-yyyy H:mm:ss,FFF",
                                                    "d-MM-yyyy HH:mm:ss,FFF",
                                                    "d-MM-yyyy H:mm:ss tt,FFF",
                                                    "d-MM-yyyy HH:mm:ss tt,FFF",
                                                    "d-M-yyyy H:mm:ss,FFF",
                                                    "d-M-yyyy HH:mm:ss,FFF",
                                                    "d-M-yyyy H:mm:ss tt,FFF",
                                                    "d-M-yyyy HH:mm:ss tt,FFF",
                                                    "dd-M-yyyy HH:mm:ss tt,FFF",
                                                    "dd-M-yyyy H:mm:ss,FFF",
                                                    "dd-M-yyyy HH:mm:ss,FFF",
                                                    "dd-M-yyyy H:mm:ss tt,FFF",
                                                    "dd-M-yyyy HH:mm:ss tt,FFF",
                                                    "M/d/yyyy H:mm:ss tt",
                                                    "M/d/yyyy H:mm tt",
                                                    "MM/dd/yyyy HH:mm:ss",
                                                    "M/d/yyyy H:mm:ss",
                                                    "M/d/yyyy HH:mm tt",
                                                    "M/d/yyyy HH tt",
                                                    "M/d/yyyy H:mm",
                                                    "M/d/yyyy H:mm",
                                                    "MM/dd/yyyy HH:mm",
                                                    "M/dd/yyyy HH:mm",
                                                    "M/dd/yyyy H:mm:ss tt",
                                                    "M/dd/yyyy H:mm:ss,FFF",
                                                    "M/dd/yyyy HH:mm:ss,FFF",
                                                    "M/dd/yyyy H:mm:ss tt,FFF",
                                                    "M/dd/yyyy HH:mm:ss tt,FFF",
                                                    "M/d/yyyy H:mm:ss,FFF",
                                                    "M/d/yyyy HH:mm:ss,FFF",
                                                    "M/d/yyyy H:mm:ss tt,FFF",
                                                    "MM/d/yyyy HH:mm:ss tt,FFF",
                                                    "MM/d/yyyy H:mm:ss,FFF",
                                                    "MM/d/yyyy HH:mm:ss,FFF",
                                                    "MM/d/yyyy H:mm:ss tt,FFF",
                                                    "MM/d/yyyy HH:mm:ss tt,FFF",
                                                    "M-d-yyyy H:mm:ss tt",
                                                    "M-d-yyyy H:mm tt",
                                                    "MM-dd-yyyy HH:mm:ss",
                                                    "M-d-yyyy H:mm:ss",
                                                    "M-d-yyyy HH:mm tt",
                                                    "M-d-yyyy HH tt",
                                                    "M-d-yyyy H:mm",
                                                    "M-d-yyyy H:mm",
                                                    "MM-dd-yyyy HH:mm",
                                                    "M-dd-yyyy HH:mm",
                                                    "M-dd-yyyy H:mm:ss,FFF",
                                                    "M-dd-yyyy HH:mm:ss,FFF",
                                                    "M-dd-yyyy H:mm:ss tt,FFF",
                                                    "M-dd-yyyy HH:mm:ss tt,FFF",
                                                    "M-d-yyyy H:mm:ss,FFF",
                                                    "M-d-yyyy HH:mm:ss,FFF",
                                                    "M-d-yyyy H:mm:ss tt,FFF",
                                                    "M-d-yyyy HH:mm:ss tt,FFF",
                                                    "MM-d-yyyy HH:mm:ss tt,FFF",
                                                    "MM-d-yyyy H:mm:ss,FFF",
                                                    "MM-d-yyyy HH:mm:ss,FFF",
                                                    "MM-d-yyyy H:mm:ss tt,FFF",
                                                    "MM-d-yyyy HH:mm:ss tt,FFF",
                                                    "yyyy/d/M H:mm:ss tt",
                                                    "yyyy/d/M H:mm tt",
                                                    "yyyy/dd/MM HH:mm:ss",
                                                    "yyyy/d/M H:mm:ss",
                                                    "yyyy/d/M HH:mm tt",
                                                    "yyyy/d/M HH tt",
                                                    "yyyy/d/M/ H:mm",
                                                    "yyyy/d/M H:mm",
                                                    "yyyy/dd/MM HH:mm",
                                                    "yyyy/d/MM HH:mm",
                                                    "yyyy/d/MM H:mm:ss,FFF",
                                                    "yyyy/d/MM HH:mm:ss,FFF",
                                                    "yyyy/d/MM H:mm:ss tt,FFF",
                                                    "yyyy/d/MM HH:mm:ss tt,FFF",
                                                    "yyyy/d/M H:mm:ss,FFF",
                                                    "yyyy/d/M HH:mm:ss,FFF",
                                                    "yyyy/d/M H:mm:ss tt,FFF",
                                                    "yyyy/dd/M HH:mm:ss tt,FFF",
                                                    "yyyy/dd/M H:mm:ss,FFF",
                                                    "yyyy/dd/M HH:mm:ss,FFF",
                                                    "yyyy/dd/M H:mm:ss tt,FFF",
                                                    "yyyy/dd/M HH:mm:ss tt,FFF",
                                                    "yyyy/MM/dd HH:mm",
                                                    "yyyy/MM/d HH:mm",
                                                    "yyyy/MM/d H:mm:ss,FFF",
                                                    "yyyy/MM/d HH:mm:ss,FFF",
                                                    "yyyy/MM/d H:mm:ss tt,FFF",
                                                    "yyyy/MM/d HH:mm:ss tt,FFF",
                                                    "yyyy/M/d H:mm:ss tt",
                                                    "yyyy/M/d H:mm tt",
                                                    "yyyy/MM/dd HH:mm:ss",
                                                    "yyyy/M/d H:mm:ss",
                                                    "yyyy/M/d HH:mm tt",
                                                    "yyyy/M/d HH tt",
                                                    "yyyy/M/d H:mm",
                                                    "yyyy/M/d H:mm",
                                                    "yyyy/M/d H:mm:ss,FFF",
                                                    "yyyy/M/d HH:mm:ss,FFF",
                                                    "yyyy/M/d H:mm:ss tt,FFF",
                                                    "yyyy/M/dd HH:mm:ss tt,FFF",
                                                    "yyyy/M/dd H:mm:ss,FFF",
                                                    "yyyy/M/dd HH:mm:ss,FFF",
                                                    "yyyy/M/dd H:mm:ss tt,FFF",
                                                    "yyyy/M/dd HH:mm:ss tt,FFF",
                                                    "yyyy-d-M H:mm:ss tt",
                                                    "yyyy-d-M H:mm tt",
                                                    "yyyy-dd-MM HH:mm:ss",
                                                    "yyyy-d-M H:mm:ss",
                                                    "yyyy-d-M HH:mm tt",
                                                    "yyyy-d-M HH tt",
                                                    "yyyy-d-M- H:mm",
                                                    "yyyy-d-M H:mm",
                                                    "yyyy-dd-MM HH:mm",
                                                    "yyyy-d-MM HH:mm",
                                                    "yyyy-d-MM H:mm:ss,FFF",
                                                    "yyyy-d-MM HH:mm:ss,FFF",
                                                    "yyyy-d-MM H:mm:ss tt,FFF",
                                                    "yyyy-d-MM HH:mm:ss tt,FFF",
                                                    "yyyy-d-M H:mm:ss,FFF",
                                                    "yyyy-d-M HH:mm:ss,FFF",
                                                    "yyyy-d-M H:mm:ss tt,FFF",
                                                    "yyyy-dd-M HH:mm:ss tt,FFF",
                                                    "yyyy-dd-M H:mm:ss,FFF",
                                                    "yyyy-dd-M HH:mm:ss,FFF",
                                                    "yyyy-dd-M H:mm:ss tt,FFF",
                                                    "yyyy-dd-M HH:mm:ss tt,FFF",
                                                    "yyyy-MM-dd HH:mm",
                                                    "yyyy-MM-d HH:mm",
                                                    "yyyy-MM-d H:mm:ss,FFF",
                                                    "yyyy-MM-d HH:mm:ss,FFF",
                                                    "yyyy-MM-d H:mm:ss tt,FFF",
                                                    "yyyy-MM-d HH:mm:ss tt,FFF",
                                                    "yyyy-M-d H:mm:ss tt",
                                                    "yyyy-M-d H:mm tt",
                                                    "yyyy-MM-dd HH:mm:ss",
                                                    "yyyy-M-d H:mm:ss",
                                                    "yyyy-M-d HH:mm tt",
                                                    "yyyy-M-d HH tt",
                                                    "yyyy-M-d H:mm",
                                                    "yyyy-M-d H:mm",
                                                    "yyyy-M-d H:mm:ss,FFF",
                                                    "yyyy-M-d HH:mm:ss,FFF",
                                                    "yyyy-M-d H:mm:ss tt,FFF",
                                                    "yyyy-M-dd HH:mm:ss tt,FFF",
                                                    "yyyy-M-dd H:mm:ss,FFF",
                                                    "yyyy-M-dd HH:mm:ss,FFF",
                                                    "yyyy-M-dd H:mm:ss tt,FFF",
                                                    "yyyy-M-dd HH:mm:ss tt,FFF",
                                                    //time formats
                                                    "H:mm:ss tt",
                                                    "H:mm tt",
                                                    "HH:mm:ss",
                                                    "HH:mm:ss tt",
                                                    "H:mm:ss",
                                                    "HH:mm tt",
                                                    "HH tt",
                                                    "H:mm",
                                                    "H:mm",
                                                    "HH:mm",
                                                    "HH:mm",
                                                    "H:mm:ss tt",
                                                    "H:mm tt",
                                                    "HH:mm:ss",
                                                    "H:mm:ss",
                                                    "HH:mm tt",
                                                    "HH tt",
                                                    "H:mm",
                                                    "H:mm",
                                                    "HH:mm",
                                                    "HH:mm",
                                                    "H:mm:ss,FFF",
                                                    "HH:mm:ss,FFF",
                                                    "H:mm:ss tt,FFF",
                                                    "HH:mm:ss tt,FFF"
        }
       .Union(CultureInfo.InvariantCulture.DateTimeFormat.GetAllDateTimePatterns()).ToArray();
        private static Logger LOGGER = LogManager.GetCurrentClassLogger();
    }
}
